### ISSUE TITLE
请问在哪里可以看到论文呢？很想学习，不知能否分享一下。

### ISSUE THREAD

**Issue by xansar** [ant-research/Spatio-Temporal-Hypergraph-Model#1]
如题。感谢！

**Comment by QiQingY** [comment]
你好，这篇文章由于会议要求，暂时没有上传至arxiv之类的地方。

鉴于在github上上传我们的文章可能会违反会议要求，所以可能只有等到7月底开完会之后，通过ACM-DL的官方途径可以看到全文，后续有公开途径，我们会及时在github里贴上链接，谢谢关注~

**Comment by QiQingY** [comment]
> 如题。感谢！

你好，这篇文章由于会议要求，暂时没有上传至arxiv之类的地方。

鉴于在github上上传我们的文章可能会违反会议要求，所以可能只有等到7月底开完会之后，通过ACM-DL的官方途径可以看到全文，后续有公开途径，我们会及时在github里贴上链接，谢谢关注~
