### ISSUE TITLE
About data preprocessing

### ISSUE THREAD

**Issue by neolifer** [ant-research/Spatio-Temporal-Hypergraph-Model#4]
Hi,
In your preprocessing 3), you divide check-in records into trajectories with 24-hour intervals. Why did you choose not to do it the more common way (fixed length trajectories)?

**Comment by QiQingY** [comment]
> Hi, In your preprocessing 3), you divide check-in records into trajectories with 24-hour intervals. Why did you choose not to do it the more common way (fixed length trajectories)?

Hi, we use the same division setting as GETNext. Fixed length trajectories may be a more different setting than other baselines.
