### ISSUE TITLE
Issue about raw.zip in ca directory

### ISSUE THREAD

**Issue by icmpnorequest** [ant-research/Spatio-Temporal-Hypergraph-Model#5]
Hi team,
Thanks for the complete processing code for the dataset. I tried to repeat the experiment on Gowalla dataset, but I got following information
```
Archive:  raw.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
note:  raw.zip may be a plain executable, not an archive
unzip:  cannot find zipfile directory in one of raw.zip or
        raw.zip.zip, and cannot find raw.zip.ZIP, period.
```
when unzipping the `ca/raw.zip`. I found and downloaded `loc-gowalla_totalCheckins.txt` and `gowalla_spots_subset1.csv` from provided link, but still cannot find `us_state_polygon_json.json`. Could you please upload the `us_state_polygon_json.json` file?

**Comment by QiQingY** [comment]
hi, apologize for the late response.
I have uploaded the `us_state_polygon_json.json` at `ca/`. Please check if you needed.

**Comment by lll0200** [comment]
Hello, after downloading ca/raw.zip, the extraction process displayed an error. Could you please re-upload ca/raw.zip? Thank you very much!
