### ISSUE TITLE
关于训练测试集划分

### ISSUE THREAD

**Issue by kevin-xuan** [ant-research/Spatio-Temporal-Hypergraph-Model#6]
你好，我当前使用的pandas是2.0.3，当再TKY数据集上运行到[df.iloc[validation_index:test_index]['SplitTag'] = 'validation'](https://github.com/ant-research/Spatio-Temporal-Hypergraph-Model/blob/main/preprocess/file_reader.py#L79)会出现SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
这个警告在于当前pandas版本用iloc进行赋值时实际上赋值的对象是df的copy版本，也就是说df并没有改变SplitTag属性值。
在这里我并没有使用你所用的低版本pandas，而是将代码改成df.loc[validation_index:test_index, ('SplitTag')] = 'validation'，很奇怪的是test_index=402813出现KeyError错误，然后分别输出验证集和测试集，发现确实没有402813，而且df.loc[validation_index:test_index-1]和df.loc[test_index-1:]的shape是[35190 rows x 15 columns]和[132494 rows x 15 columns]，验证集是没问题的，测试集的长度却太奇怪了，结果如下：
<img width="804" alt="截屏2024-03-25 18 55 08" src="https://github.com/ant-research/Spatio-Temporal-Hypergraph-Model/assets/87954969/598069d7-647e-422c-8d3f-11fe1b0797b9">
然后我单独打印df.loc[402812:total_len]，shape是[34708 rows x 15 columns]，这又是对的了。唯一的差别在于total_len的限制，结果如下：
<img width="802" alt="截屏2024-03-25 18 58 31" src="https://github.com/ant-research/Spatio-Temporal-Hypergraph-Model/assets/87954969/92a8fc62-2952-4ec5-a252-2990526eb707">
我做出的修改部分如下，其余部分我都没改动：
<img width="795" alt="截屏2024-03-25 19 06 30" src="https://github.com/ant-research/Spatio-Temporal-Hypergraph-Model/assets/87954969/5991cb6b-6f7e-427c-92f6-354cbfac7e94">
这个结果太奇怪了，是pandas版本导致的各种函数都改变了嘛？但是却只出现了一个警告SettingWithCopyWarning。

**Comment by kevin-xuan** [comment]
不好意思，是我弄错了loc和iloc的机制，loc是标签索引，所以test_index=402813出现KeyError错误，因为没有这一个line label。而iloc是数字索引，是直接选择多行，与标签无关。但如果高版本的pandas用这份代码的话仍然会出现赋值警告，确切地说其实应该直接报错，因为赋值失败了。正确的做法应该是这样的：
df.iloc[validation_index:test_index, -1] = 'validation'  # -1即'SplitTag'
df.iloc[test_index:, -1] = 'test'
不过我还有一个疑问，在我最后那个截图那里df = df.sort_values(by='UTCTimeOffset', ascending=True)是按时间戳将所有用户的check-ins进行排序，然后将最后0.2作为验证测试集。但正常来说应该是按时间戳将单个用户的check-ins进行排序，然后按8:1:1进行划分。如果一个用户的check-in时间很晚，那他极有可能被划分到验证测试集中而训练集没有。或者说他的check-ins数量很少且很早，那他全部都在训练集中。我不清楚你的这种划分方式会不会出现这个情况，有空的话能解释下吗？

**Comment by QiQingY** [comment]
Hi, kevin，
直接按照时间做排序的话，确实会存在有一些用户只在测试上的情况。

我们试过两种划分，效果来讲的话，差别不大，你也可以试试改你的截图的代码那几行就可以。
